In [0]:
import torch
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x = torch.ones(2, 3)
y = torch.zeros(4, 2)
print(x, y)

tensor([[1., 1., 1.],
        [1., 1., 1.]]) tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


In [0]:
x = torch.empty(2, 3)

In [4]:
print(x)

tensor([[6.8282e-36, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [5]:
x = torch.zeros_like(x)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
y = torch.linspace(0, 10, 11)
print(y)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [7]:
x = torch.randn(2, 3)
print(x)

tensor([[ 1.3589, -0.6765,  1.8811],
        [ 0.3075,  1.2231, -0.2550]])


In [0]:
x = torch.tensor([[1, 2], [2, 3], [4, 5]])

In [9]:
print(x)

tensor([[1, 2],
        [2, 3],
        [4, 5]])


In [10]:
x.size()
y = x[:, 1]
z = x[:, :]
print(y, z)

tensor([2, 3, 5]) tensor([[1, 2],
        [2, 3],
        [4, 5]])


In [11]:
y = x.view(2, 3)
z = x.view(1, -1)
print(y, z)
y = x[0, 1]
print(y)
print(y.item())


tensor([[1, 2, 2],
        [3, 4, 5]]) tensor([[1, 2, 2, 3, 4, 5]])
tensor(2)
2


In [12]:
x = torch.ones(3, 2)
y = torch.ones(3, 2)
z = x+y
print(z)
z = x.add(y)
z= y.add_(x)
print(x, y, z)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]]) tensor([[2., 2.],
        [2., 2.],
        [2., 2.]]) tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


In [13]:
x_np = x.numpy()
x_np += 5
print(x, x_np)
print(type(x), type(x_np))

tensor([[6., 6.],
        [6., 6.],
        [6., 6.]]) [[6. 6.]
 [6. 6.]
 [6. 6.]]
<class 'torch.Tensor'> <class 'numpy.ndarray'>


In [14]:
a = np.random.randn(2, 3)
a_np = torch.from_numpy(a)
a += 2
print(a, a_np)

[[3.27797929 1.89251356 1.88067882]
 [0.50008506 1.7455188  0.73214118]] tensor([[3.2780, 1.8925, 1.8807],
        [0.5001, 1.7455, 0.7321]], dtype=torch.float64)


In [15]:
%%time
for i in range(10):
  x = np.random.randn(50, 50)
  y = np.random.randn(50, 50)
  z = np.matmul(x, y)
print(x.shape)

(50, 50)
CPU times: user 3.74 ms, sys: 0 ns, total: 3.74 ms
Wall time: 9.76 ms


In [16]:
%%time
for i in range(40):
  x = torch.randn(50, 50)
  y = torch.randn(50, 50)
  z = x * y

CPU times: user 3.44 ms, sys: 0 ns, total: 3.44 ms
Wall time: 3.51 ms


In [17]:
print(torch.cuda.device_count())

1


In [18]:
print(torch.cuda.device(0))
print(torch.cuda.get_device_name(0))

Tesla K80


In [0]:
cuda0 = torch.device("cuda:0")

In [20]:
x = torch.randn(2, 3, device=cuda0)
y = torch.randn(2, 1, device=cuda0)
z = x + y
print(z)

tensor([[ 1.8752,  0.0266,  1.0036],
        [-0.1947, -2.1048, -1.3507]], device='cuda:0')


In [21]:
x = torch.ones(2, 3)
y = torch.ones((2, 3))
z = torch.ones([2, 3])
print(x.shape, y.shape, z.shape)

torch.Size([2, 3]) torch.Size([2, 3]) torch.Size([2, 3])


In [22]:
x = torch.ones((2, 3), requires_grad=True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [23]:
y = x + 10
print(y)

tensor([[11., 11., 11.],
        [11., 11., 11.]], grad_fn=<AddBackward0>)


In [24]:
z = y * 7
print(z)

tensor([[77., 77., 77.],
        [77., 77., 77.]], grad_fn=<MulBackward0>)


In [25]:
r = torch.sum(z)
print(r)

tensor(462., grad_fn=<SumBackward0>)


In [0]:
r.backward()

In [27]:
print(x.grad)

tensor([[7., 7., 7.],
        [7., 7., 7.]])


In [28]:
x = torch.randn((2, 3), requires_grad=True)
print(x)

tensor([[ 1.4149, -2.1585, -0.9209],
        [-1.4367, -2.5882, -1.4416]], requires_grad=True)


In [29]:
y = x ** 2
print(y)

tensor([[2.0020, 4.6591, 0.8480],
        [2.0640, 6.6990, 2.0781]], grad_fn=<PowBackward0>)


In [30]:
z = y * 2
print(z)

tensor([[ 4.0040,  9.3181,  1.6961],
        [ 4.1280, 13.3980,  4.1562]], grad_fn=<MulBackward0>)


In [0]:
t = torch.ones(2, 3)
z.backward(t)


In [32]:
print(x.grad)

tensor([[  5.6597,  -8.6340,  -3.6836],
        [ -5.7467, -10.3530,  -5.7663]])


In [0]:
x = torch.randn((20, 1), requires_grad = True)
y = 3*x - 2

In [0]:
w = torch.tensor([4.], requires_grad=True)
b = torch.tensor([-2.], requires_grad=True)
y_pred = w * x + b
loss = torch.sum((y_pred - y)**2)

In [35]:
print(loss)

tensor(24.1069, grad_fn=<SumBackward0>)


In [0]:
loss.backward()

In [37]:
print(w.grad)
print(b.grad)

tensor([48.2139])
tensor([-1.7331])


In [79]:
%%time
learning_rate = 0.001
N = 10000000
epochs = 200

w = torch.rand([N], requires_grad=True, device=cuda0)
b = torch.ones([1], requires_grad=True, device=cuda0)

# print(torch.mean(w).item(), b.item())

for i in range(epochs):
  
  x = torch.randn([N], device=cuda0)
  y = torch.dot(3*torch.ones([N], device=cuda0), x) - 2
  
  y_hat = torch.dot(w, x) + b
  loss = torch.sum((y_hat - y)**2)
  
  loss.backward()
  
  with torch.no_grad():
    w -= learning_rate * w.grad
    b -= learning_rate * b.grad
    
    w.grad.zero_()
    b.grad.zero_()

  #print(torch.mean(w).item(), b.item())
  

CPU times: user 790 ms, sys: 492 ms, total: 1.28 s
Wall time: 1.3 s


In [80]:
torch.dot(3*torch.ones([10]), torch.randn([10], requires_grad=True, device=cuda0))

RuntimeError: ignored